# Generated by Django 4.0.6 on 2022-07-28 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slot',
        ),
        migrations.AddField(
            model_name='room',
            name='slots',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Slots'),
        ),
    ]
