# Generated by Django 4.0.6 on 2022-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_slot_room_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Password'),
        ),
    ]
